version: "3"
services:
  apache-php:
    build:
      context: ./
    container_name: apache-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./phpcon:/usr/local/etc/php
    depends_on:
      - mysql
    networks:
      - php-mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hola1234
      MYSQL_DATABASE:  testBasedeDatos
    networks:
      - php-mysql

networks:
  php-mysql:
    driver: bridge
